# name: Notify Slack on Release

# on:
#   release:
#     types:
#       - created
#       - push

# jobs:
#   notify_slack:
#     runs-on: ubuntu-latest
#     name: Notify Slack on Release
#     steps:
#       - name: Notify Slack on Release
#         uses: instantish/notify-slack-on-release@1.0.0
#         with:
#           slack_webhook_url: ${{ secrets.SLACK }}

# name: slack_github_action
# on: 
#   release:
#     types:
#       - created
#       - push
#       - pull_request
# jobs:
#   slack_notifier:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Send notification on Slack using Webhooks
#         uses: slackapi/slack-github-action@v1.24.0
#         with:
#           payload: |
#             {
#             "text": "Git push done in the repo , and PR is created"
#             }
#         env:
##           SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}

# name: Slack Notifications for Pull Requests

# on:
#   pull_request:
#     types: [opened]

# jobs:
#   notify_slack:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Notify Slack
#         uses: slackapi/slack-github-action@v1.24.0
#         with:
#           payload: |
#             {
#             "text": "PR is created"
#             }
#         env:
#           SLACK_WEBHOOK_URL: ${{ secrets.SLACK }}
#           channel: 'github'
#           username: 'GitHub Actions'
#           icon_emoji: ':rocket:'
#           text: 'New pull request created: ${{ github.event.pull_request.html_url }}'

# name: Slack Pull Request Open Notification

# on:
#   pull_request:
#     types: [opened, reopened]

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Notify slack pr open
#       env: 
#         SLACK_WEBHOOK_URL : ${{ secrets.SLACK }}
#         PULL_REQUEST_NUMBER : ${{ github.event.pull_request.number }}
#         PULL_REQUEST_TITLE : ${{ github.event.pull_request.title }}
#         PULL_REQUEST_AUTHOR_NAME : ${{ github.event.pull_request.user.login }}
#         PULL_REQUEST_AUTHOR_ICON_URL : ${{ github.event.pull_request.user.avatar_url }}
#         PULL_REQUEST_URL : ${{ github.event.pull_request.html_url }}
#         PULL_REQUEST_BODY : ${{ github.event.pull_request.body }}
#         PULL_REQUEST_COMPARE_BRANCH_OWNER: ${{ github.event.pull_request.head.repo.owner.login }}
#         PULL_REQUEST_COMPARE_BRANCH_NAME : ${{ github.event.pull_request.head.ref }}
#         PULL_REQUEST_BASE_BRANCH_OWNER: ${{ github.event.pull_request.base.repo.owner.login }}
#         PULL_REQUEST_BASE_BRANCH_NAME : ${{ github.event.pull_request.base.ref }}
#         IS_SEND_HERE_MENTION : true
#         MAKE_PRETTY : false
#         MAKE_COMPACT : false
#         IS_PR_FROM_FORK: false
#         # SEND_USER_ID_MENTIONS : ABCDE12345,AAABBBCCCC
#         # SEND_GROUP_ID_MENTIONS : GROUPIDDDD,GGGGROUPID
#       uses: jun3453/slack-pr-open-notification-action@v1.3.0

name: Slack Integration

on:
  pull_request:
    types: [opened, reopened, ready_for_review, closed]
  issues:
    types: [opened, reopened, closed]
  pull_request_review:
    types: [submitted]
  issue_comment:
    types: [created]

jobs:
  slack-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/slack-integration@v1
        with:
          slack-token: ${{ secrets.SLACK }}
          channel: 'github'
          subscribe-pulls: true
          subscribe-issues: true
          subscribe-reviews: true
          subscribe-pull-comments: true
          subscribe-issue-comments: true
